name: 'salesforce_source_integration_tests'
version: '1.0.1'

config-version: 2

profile: 'integration_tests'

models:
  +schema: "salesforce_source_{{ var('directed_schema','dev') }}"

vars:
  salesforce_source:
    salesforce_schema: zz_dbt_catherine_sf # salesforce_source_integrations_tests_3
    salesforce_history_schema: zz_dbt_catherine_sf # salesforce_source_integrations_tests_3

    salesforce_account_identifier: "sf_account_data"
    salesforce_opportunity_identifier: "sf_opportunity_data"
    salesforce_user_identifier: "sf_user_data"
    salesforce_user_role_identifier: "sf_user_role_data"
    salesforce_contact_identifier: "sf_contact_data"
    salesforce_lead_identifier: "sf_lead_data"
    salesforce_task_identifier: "sf_task_data"
    salesforce_event_identifier: "sf_event_data"
    salesforce_product_2_identifier: "sf_product_2_data"
    salesforce_order_identifier: "sf_order_data"
    salesforce_opportunity_line_item_identifier: "sf_opportunity_line_item_data"

    ##history mode identifiers
    salesforce_account_history_identifier: "sf_account_history_data"
    salesforce_contact_history_identifier: "sf_contact_history_data"
    salesforce_opportunity_history_identifier: "sf_opportunity_history_data"

    salesforce__account_history_enabled: false
    salesforce__contact_history_enabled: false
    salesforce__opportunity_history_enabled: false

seeds:
  salesforce_source_integration_tests:
    +quote_columns: "{{ true if target.type in ('redshift', 'postgres') else false }}"
    +column_types:
      _fivetran_synced: timestamp
      _fivetran_active: boolean
      _fivetran_start: timestamp
      _fivetran_end: timestamp
    sf_account_data:
      +column_types:
        last_activity_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        account_number: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        annual_revenue: float
        billing_latitude: float
        billing_longitude: float
        parent_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        product_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        shipping_city: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        shipping_country: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        shipping_country_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        shipping_postal_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        shipping_state: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        shipping_state_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        shipping_street: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        shipping_latitude: float
        shipping_longitude: float
    sf_opportunity_data:
      +column_types:
        amount: float
        campaign_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        close_date: timestamp
        converted_account_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        converted_contact_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        converted_opportunity_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        created_by_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        created_date: timestamp
        individual_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        last_activity_date: timestamp
        last_modified_by_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        master_record_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        mobile_phone: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        next_step: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        owner_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        phone: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        postal_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        probability: float
        state_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        synced_quote_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
    sf_user_data:
      +column_types:
        account_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        company_name: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        contact_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        country_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        individual_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        last_login_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        latitude: float
        longitude: float
        manager_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        offline_trial_expiration_date: timestamp
        postal_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        profile_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        state_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        user_role_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
    sf_contact_data:
      +column_types:
        birthdate: timestamp
        created_date: timestamp
        email_bounced_date: timestamp
        home_phone: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        individual_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        is_deleted: boolean
        last_activity_date: timestamp
        last_curequest_date: timestamp
        last_cuupdate_date: timestamp
        last_modified_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        mailing_postal_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        master_record_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        mobile_phone: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        reports_to_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        system_modstamp: timestamp
    sf_lead_data:
      +column_types:
        converted_date: timestamp
        converted_opportunity_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        country_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        created_date: timestamp
        email_bounced_date: timestamp
        email_bounced_reason: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        individual_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        last_activity_date: timestamp
        last_modified_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        lead_source: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        master_record_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        mobile_phone: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        owner_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        phone: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        postal_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        state_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        system_modstamp: timestamp
        is_deleted: boolean
    sf_task_data:
      +column_types:
        account_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        activity_date: timestamp
        call_disposition: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        call_object: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        call_type: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        completed_date_time: timestamp
        created_by_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        created_date: timestamp
        is_deleted: boolean
        last_modified_by_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        last_modified_date: timestamp
        owner_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        record_type_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        recurrence_end_date_only: timestamp
        recurrence_start_date_only: timestamp
        reminder_date_time: timestamp
        system_modstamp: timestamp
        what_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        who_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
    sf_event_data:
      +column_types:
        activity_date: timestamp
        activity_date_time: timestamp
        created_date: timestamp
        end_date: timestamp
        end_date_time: timestamp
        group_event_type: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        last_modified_date   : timestamp
        recurrence_2_pattern_start_date   : timestamp
        recurrence_end_date_only: timestamp
        recurrence_start_date_time: timestamp
        reminder_date_time: timestamp
        start_date_time: timestamp
        system_modstamp: timestamp
        is_deleted: boolean
    sf_product_2_data:
      +column_types:
        created_by_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        created_date: timestamp
        display_url: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        external_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        is_deleted: boolean
        last_modified_by_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        last_modified_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        product_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        quantity_installment_period: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        quantity_schedule_type: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        quantity_unit_of_measure: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        record_type_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        revenue_installment_period: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        revenue_schedule_type: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        system_modstamp: timestamp
    sf_order_data:
      +column_types:
        account_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        activated_by_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        activated_date: timestamp
        billing_country_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        billing_state_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        contract_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        created_by_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        created_date: timestamp
        effective_date: timestamp
        end_date: timestamp
        is_deleted: boolean
        last_modified_by_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        last_modified_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        opportunity_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        order_number: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        original_order_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        owner_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        pricebook_2_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        shipping_country_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        shipping_postal_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        shipping_state_code: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        system_modstamp: timestamp
    sf_opportunity_line_item_data:
      +column_types:
        campaign_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}" 
        created_by_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        created_date: timestamp
        has_quantity_schedule: boolean
        has_revenue_schedule: boolean
        has_schedule: boolean
        is_deleted: boolean
        last_modified_by_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        last_modified_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        opportunity_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        product_2_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"
        service_date: timestamp
        system_modstamp: timestamp
    sf_user_role_data:
      +column_types:
        parent_role_id: "{{ 'string' if target.name in ['bigquery','spark', 'databricks'] else 'varchar' }}"

    sf_account_history_data:
      +column_types:
        annual_revenue: float
        last_activity_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        is_deleted: boolean
    sf_contact_history_data:
      +column_types:
        birthdate: timestamp
        last_activity_date: timestamp 
        last_modified_date: timestamp 
        last_viewed_date: timestamp
        is_deleted: boolean
    sf_opportunity_history_data:
      +column_types:
        close_date: timestamp
        created_date: timestamp
        last_activity_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        amount: float
        expected_revenue: float
        is_deleted: boolean

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']