{% macro get_contact_columns() %}

{% set columns = [
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "_fivetran_active", "datatype": dbt.type_boolean()},
    {"name": "account_id", "datatype": dbt.type_string()},
    {"name": "accountid", "datatype": dbt.type_string()},
    {"name": "department", "datatype": dbt.type_string()},
    {"name": "description", "datatype": dbt.type_string()},
    {"name": "email", "datatype": dbt.type_string()},
    {"name": "first_name", "datatype": dbt.type_string()},
    {"name": "firstname", "datatype": dbt.type_string()},
    {"name": "home_phone", "datatype": dbt.type_string()},
    {"name": "homephone", "datatype": dbt.type_string()},
    {"name": "id", "datatype": dbt.type_string()},
    {"name": "individual_id", "datatype": dbt.type_string()},
    {"name": "individualid", "datatype": dbt.type_string()},
    {"name": "is_deleted", "datatype": dbt.type_boolean()},
    {"name": "isdeleted", "datatype": dbt.type_boolean()},
    {"name": "last_activity_date", "datatype": dbt.type_timestamp()},
    {"name": "lastactivitydate", "datatype": dbt.type_timestamp()},
    {"name": "last_modified_by_id", "datatype": dbt.type_string()},
    {"name": "lastmodifiedbyid", "datatype": dbt.type_string()},
    {"name": "last_modified_date", "datatype": dbt.type_timestamp()},
    {"name": "lastmodifieddate", "datatype": dbt.type_timestamp()},
    {"name": "last_name", "datatype": dbt.type_string()},
    {"name": "lastname", "datatype": dbt.type_string()},
    {"name": "last_referenced_date", "datatype": dbt.type_timestamp()},
    {"name": "lastreferenceddate", "datatype": dbt.type_timestamp()},
    {"name": "last_viewed_date", "datatype": dbt.type_timestamp()},
    {"name": "lastvieweddate", "datatype": dbt.type_timestamp()},
    {"name": "lead_source", "datatype": dbt.type_string()},
    {"name": "leadsource", "datatype": dbt.type_string()},
    {"name": "mailing_city", "datatype": dbt.type_string()},
    {"name": "mailingcity", "datatype": dbt.type_string()},
    {"name": "mailing_country", "datatype": dbt.type_string()},
    {"name": "mailingcountry", "datatype": dbt.type_string()},
    {"name": "mailing_country_code", "datatype": dbt.type_string()},
    {"name": "mailingcountrycode", "datatype": dbt.type_string()},
    {"name": "mailing_postal_code", "datatype": dbt.type_string()},
    {"name": "mailingpostalcode", "datatype": dbt.type_string()},
    {"name": "mailing_state", "datatype": dbt.type_string()},
    {"name": "mailingstate", "datatype": dbt.type_string()},
    {"name": "mailing_state_code", "datatype": dbt.type_string()},
    {"name": "mailingstatecode", "datatype": dbt.type_string()},
    {"name": "mailing_street", "datatype": dbt.type_string()},
    {"name": "mailingstreet", "datatype": dbt.type_string()},
    {"name": "master_record_id", "datatype": dbt.type_string()},
    {"name": "masterrecordid", "datatype": dbt.type_string()},
    {"name": "mobile_phone", "datatype": dbt.type_string()},
    {"name": "mobilephone", "datatype": dbt.type_string()},
    {"name": "name", "datatype": dbt.type_string()},
    {"name": "owner_id", "datatype": dbt.type_string()},
    {"name": "ownerid", "datatype": dbt.type_string()},
    {"name": "phone", "datatype": dbt.type_string()},
    {"name": "reports_to_id", "datatype": dbt.type_string()},
    {"name": "reportstoid", "datatype": dbt.type_string()},
    {"name": "title", "datatype": dbt.type_string()}
] %}

{{ fivetran_utils.add_pass_through_columns(columns, var('salesforce__contact_pass_through_columns')) }}        

{{ return(columns) }}

{% endmacro %}
