18:29:54  {% macro get_opportunity_line_item_columns() %}

{% set columns = [
    {"name": "_fivetran_synced", "datatype": dbt_utils.type_timestamp()},
    {"name": "celigo_sfnsio_contract_item_id_c", "datatype": dbt_utils.type_string()},
    {"name": "celigo_sfnsio_contract_term_c", "datatype": dbt_utils.type_float()},
    {"name": "celigo_sfnsio_end_date_c", "datatype": dbt_utils.type_timestamp()},
    {"name": "celigo_sfnsio_list_rate_c", "datatype": dbt_utils.type_numeric()},
    {"name": "celigo_sfnsio_net_suite_line_id_c", "datatype": dbt_utils.type_string()},
    {"name": "celigo_sfnsio_start_date_c", "datatype": dbt_utils.type_timestamp()},
    {"name": "created_by_id", "datatype": dbt_utils.type_string()},
    {"name": "created_date", "datatype": dbt_utils.type_timestamp()},
    {"name": "description", "datatype": dbt_utils.type_string()},
    {"name": "discount", "datatype": dbt_utils.type_float()},
    {"name": "event_volume_c", "datatype": dbt_utils.type_float()},
    {"name": "has_quantity_schedule", "datatype": "boolean"},
    {"name": "has_revenue_schedule", "datatype": "boolean"},
    {"name": "has_schedule", "datatype": "boolean"},
    {"name": "hvr_use_case_c", "datatype": "boolean"},
    {"name": "id", "datatype": dbt_utils.type_string()},
    {"name": "is_deleted", "datatype": "boolean"},
    {"name": "last_modified_by_id", "datatype": dbt_utils.type_string()},
    {"name": "last_modified_date", "datatype": dbt_utils.type_timestamp()},
    {"name": "last_referenced_date", "datatype": dbt_utils.type_timestamp()},
    {"name": "last_viewed_date", "datatype": dbt_utils.type_timestamp()},
    {"name": "list_price", "datatype": dbt_utils.type_float()},
    {"name": "months_c", "datatype": dbt_utils.type_float()},
    {"name": "name", "datatype": dbt_utils.type_string()},
    {"name": "netsuite_conn_discount_item_c", "datatype": dbt_utils.type_string()},
    {"name": "netsuite_conn_end_date_c", "datatype": dbt_utils.type_timestamp()},
    {"name": "netsuite_conn_from_contract_item_id_c", "datatype": dbt_utils.type_string()},
    {"name": "netsuite_conn_item_category_c", "datatype": dbt_utils.type_string()},
    {"name": "netsuite_conn_list_rate_c", "datatype": dbt_utils.type_float()},
    {"name": "netsuite_conn_net_suite_item_id_import_c", "datatype": dbt_utils.type_string()},
    {"name": "netsuite_conn_net_suite_item_key_id_c", "datatype": dbt_utils.type_string()},
    {"name": "netsuite_conn_pushed_from_net_suite_c", "datatype": "boolean"},
    {"name": "netsuite_conn_start_date_c", "datatype": dbt_utils.type_timestamp()},
    {"name": "netsuite_conn_term_contract_pricing_type_c", "datatype": dbt_utils.type_string()},
    {"name": "netsuite_conn_terms_c", "datatype": dbt_utils.type_float()},
    {"name": "netsuite_conn_user_entered_sales_price_c", "datatype": dbt_utils.type_float()},
    {"name": "one_saas_app_included_c", "datatype": "boolean"},
    {"name": "one_saas_app_quantity_invoiced_c", "datatype": dbt_utils.type_float()},
    {"name": "one_saas_app_quantity_not_invoiced_c", "datatype": dbt_utils.type_float()},
    {"name": "opportunity_id", "datatype": dbt_utils.type_string()},
    {"name": "pricebook_entry_id", "datatype": dbt_utils.type_string()},
    {"name": "product_2_id", "datatype": dbt_utils.type_string()},
    {"name": "product_code", "datatype": dbt_utils.type_string()},
    {"name": "product_code_stamped_c", "datatype": dbt_utils.type_string()},
    {"name": "product_family_c", "datatype": dbt_utils.type_string()},
    {"name": "quantity", "datatype": dbt_utils.type_float()},
    {"name": "roadmap_connections_c", "datatype": dbt_utils.type_float()},
    {"name": "row_volume_c", "datatype": dbt_utils.type_float()},
    {"name": "sbqq_parent_id_c", "datatype": dbt_utils.type_string()},
    {"name": "sbqq_quote_line_c", "datatype": dbt_utils.type_string()},
    {"name": "sbqq_subscription_type_c", "datatype": dbt_utils.type_string()},
    {"name": "service_date", "datatype": dbt_utils.type_timestamp()},
    {"name": "sort_order", "datatype": dbt_utils.type_int()},
    {"name": "system_modstamp", "datatype": dbt_utils.type_timestamp()},
    {"name": "total_price", "datatype": dbt_utils.type_float()},
    {"name": "unit_price", "datatype": dbt_utils.type_float()}
] %}

{{ return(columns) }}

{% endmacro %}
