{% macro get_opportunity_history_columns() %}

{% set columns = [
    {"name": "_fivetran_active", "datatype": "boolean"},
    {"name": "_fivetran_end", "datatype": dbt.type_timestamp()},
    {"name": "_fivetran_start", "datatype": dbt.type_timestamp()},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "account_id", "datatype": dbt.type_string()},
    {"name": "age_in_days", "datatype": dbt.type_int()},
    {"name": "amount", "datatype": dbt.type_float()},
    {"name": "campaign_id", "datatype": dbt.type_string()},
    {"name": "close_date", "datatype": "date"},
    {"name": "contact_id", "datatype": dbt.type_string()},
    {"name": "contract_id", "datatype": dbt.type_string()},
    {"name": "created_by_id", "datatype": dbt.type_string()},
    {"name": "created_date", "datatype": dbt.type_timestamp()},
    {"name": "description", "datatype": dbt.type_string()},
    {"name": "expected_revenue", "datatype": dbt.type_float()},
    {"name": "fiscal", "datatype": dbt.type_string()},
    {"name": "fiscal_quarter", "datatype": dbt.type_int()},
    {"name": "fiscal_year", "datatype": dbt.type_int()},
    {"name": "forecast_category", "datatype": dbt.type_string()},
    {"name": "forecast_category_name", "datatype": dbt.type_string()},
    {"name": "has_open_activity", "datatype": "boolean"},
    {"name": "has_opportunity_line_item", "datatype": "boolean"},
    {"name": "has_overdue_task", "datatype": "boolean"},
    {"name": "id", "datatype": dbt.type_string()},
    {"name": "is_closed", "datatype": "boolean"},
    {"name": "is_deleted", "datatype": "boolean"},
    {"name": "is_excluded_from_territory_2_filter", "datatype": "boolean"},
    {"name": "is_priority_record", "datatype": "boolean"},
    {"name": "is_private", "datatype": "boolean"},
    {"name": "is_won", "datatype": "boolean"}, 
    {"name": "last_activity_date", "datatype": "date"},
    {"name": "last_activity_in_days", "datatype": dbt.type_int()},
    {"name": "last_amount_changed_history_id", "datatype": dbt.type_string()},
    {"name": "last_close_date_changed_history_id", "datatype": dbt.type_string()},
    {"name": "last_modified_by_id", "datatype": dbt.type_string()},
    {"name": "last_modified_date", "datatype": dbt.type_timestamp()},
    {"name": "last_referenced_date", "datatype": dbt.type_timestamp()},
    {"name": "last_stage_change_date", "datatype": dbt.type_timestamp()},
    {"name": "last_stage_change_in_days", "datatype": dbt.type_int()},
    {"name": "last_viewed_date", "datatype": dbt.type_timestamp()}, 
    {"name": "lead_source", "datatype": dbt.type_string()}, 
    {"name": "name", "datatype": dbt.type_string()},
    {"name": "next_step", "datatype": dbt.type_string()}, 
    {"name": "owner_id", "datatype": dbt.type_string()}, 
    {"name": "pricebook_2_id", "datatype": dbt.type_string()}, 
    {"name": "probability", "datatype": dbt.type_float()},
    {"name": "push_count", "datatype": dbt.type_int()}, 
    {"name": "record_type_id", "datatype": dbt.type_string()},
    {"name": "stage_name", "datatype": dbt.type_string()},
    {"name": "synced_quote_id", "datatype": dbt.type_string()},
    {"name": "system_modstamp", "datatype": dbt.type_timestamp()}, 
    {"name": "territory_2_id", "datatype": dbt.type_string()},
    {"name": "total_opportunity_quantity", "datatype": dbt.type_float()},
    {"name": "type", "datatype": dbt.type_string()}
] %}

{{ return(columns) }}

{% endmacro %}