
with base as (

    select * 
    from {{ ref('stg_salesforce__order_tmp') }}
),

fields as (

    select
        {{
            fivetran_utils.fill_staging_columns(
                source_columns=adapter.get_columns_in_relation(ref('stg_salesforce__order_tmp')),
                staging_columns=get_order_columns()
            )
        }}
    from base
),

final as (
    
    select 
18:30:59          _fivetran_synced,
        account_id,
        activated_by_id,
        activated_date,
        amend_with_rollover_spend_type_c,
        amendment_type_c,
        ava_sfcpq_ava_tax_message_c,
        ava_sfcpq_entity_use_code_c,
        ava_sfcpq_invoice_message_c,
        ava_sfcpq_is_seller_importer_of_record_c,
        ava_sfcpq_order_calculate_tax_c,
        ava_sfcpq_sales_tax_amount_c,
        billing_city,
        billing_country,
        billing_country_code,
        billing_geocode_accuracy,
        billing_latitude,
        billing_longitude,
        billing_postal_code,
        billing_state,
        billing_state_code,
        billing_street,
        blng_bill_now_c,
        blng_billing_account_c,
        blng_billing_day_of_month_c,
        blng_invoice_batch_c,
        celigo_sfnsio_discount_total_net_suite_c,
        celigo_sfnsio_net_suite_id_c,
        celigo_sfnsio_net_suite_order_number_c,
        celigo_sfnsio_net_suite_order_status_c,
        celigo_sfnsio_net_suite_record_c,
        celigo_sfnsio_ship_date_c,
        celigo_sfnsio_skip_export_to_net_suite_c,
        celigo_sfnsio_sub_total_net_suite_c,
        celigo_sfnsio_tax_total_net_suite_c,
        celigo_sfnsio_test_mode_record_c,
        celigo_sfnsio_total_net_suite_c,
        company_authorized_by_id,
        contract_id,
        created_by_id,
        created_date,
        credit_summary_c,
        customer_authorized_by_id,
        customer_spend_type_c,
        description,
        effective_date,
        end_date,
        evergreen_c,
        id,
        invoicing_type_c,
        is_deleted,
        is_hvr_legacy_order_c,
        is_reduction_order,
        last_modified_by_id,
        last_modified_date,
        last_referenced_date,
        last_viewed_date,
        legal_entity_c,
        netsuite_conn_celigo_update_c,
        netsuite_conn_discount_total_c,
        netsuite_conn_document_id_c,
        netsuite_conn_net_suite_id_c,
        netsuite_conn_net_suite_order_date_c,
        netsuite_conn_net_suite_order_number_c,
        netsuite_conn_net_suite_order_status_c,
        netsuite_conn_net_suite_sync_err_c,
        netsuite_conn_opportunity_c,
        netsuite_conn_push_to_net_suite_c,
        netsuite_conn_pushed_from_net_suite_c,
        netsuite_conn_quote_c,
        netsuite_conn_ship_date_c,
        netsuite_conn_subtotal_c,
        netsuite_conn_sync_in_progress_c,
        netsuite_conn_tax_total_c,
        netsuite_conn_total_c,
        netsuite_conn_tracking_numbers_c,
        opportunity_id,
        order_auto_activated_c,
        order_number,
        order_spend_type_c,
        original_order_id,
        owner_id,
        prepaid_billing_frequency_c,
        prepaid_order_c,
        pricebook_2_id,
        purchase_order_number_c,
        purchase_summary_c,
        sbqq_contracted_c,
        sbqq_contracting_method_c,
        sbqq_payment_term_c,
        sbqq_price_calc_status_c,
        sbqq_price_calc_status_message_c,
        sbqq_quote_c,
        sbqq_renewal_term_c,
        sbqq_renewal_uplift_rate_c,
        shipping_city,
        shipping_country,
        shipping_country_code,
        shipping_geocode_accuracy,
        shipping_latitude,
        shipping_longitude,
        shipping_postal_code,
        shipping_state,
        shipping_state_code,
        shipping_street,
        status,
        status_code,
        synced_to_net_suite_c,
        system_modstamp,
        total_amount,
        type,
        update_subscriptions_only_c
    from fields
)

select *
from final
